import turtle
t=turtle.Turtle()
t.up()
t.left(90)
t.forward(200)
t.right(90)
t.down()
#first
t.color("orange")
t.begin_fill()
for i in range(2):
    t.forward(500)
    t.right(90)
    t.forward(100)
    t.right(90)
t.end_fill()
t.up()
t.right(90)
t.forward(100)
t.down()
#second
t.color("white")
t.begin_fill()
for i in range(2):
    t.forward(100)
    t.left(90)
    t.forward(500)
    t.left(90)
t.end_fill()
t.up()
t.forward(100)
t.down()
#third
t.color("green")
t.begin_fill()
for i in range(2):
    t.forward(100)
    t.left(90)
    t.forward(500)
    t.left(90)
t.end_fill()
t.color("black")
t.begin_fill()
t.forward(300)
t.end_fill()
t.up()
t.right(180)
t.forward(350)
t.right(90)
t.forward(250)
#long line
t.down()
t.right(20)
t.left(20)
#circle
t.up()
t.forward(50)
t.right(20)
t.left(20)
t.up()
t.left(90)
t.down()
t.pensize(2)
t.circle(40)
#Ashok Chakra
t.up()
t.left(90)
t.fd(40)
t.down()
t.pensize(2)
t.color("blue")
t.begin_fill()
for i in range(24):
    t.forward(40)
    t.backward(40)
    t.left(15)
t.end_fill()
